resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers
    workers

    [managers:children]
    active

    [active]
    node01.netology.oci ansible_host=${oci_core_instance.node[0].public_ip}

    [workers]
    node02.netology.oci ansible_host=${oci_core_instance.node[1].public_ip}
    node03.netology.oci ansible_host=${oci_core_instance.node[2].public_ip}
    node04.netology.oci ansible_host=${oci_core_instance.node[3].public_ip}
    DOC
  filename = "../ansible/inventory"
  file_permission = "0644"

  depends_on = [
    oci_core_instance.node[0],
    oci_core_instance.node[1],
    oci_core_instance.node[2],
    oci_core_instance.node[3]
  ]
}
